import os

spells_data = [
    # Cantrips
    {
        "title": "Fire Bolt",
        "slug": "fire-bolt",
        "level": 0,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "120 feet",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": True,
        "upcast_notes": "Deals 2d10 Fire at Level 7 (scales to 3d10 at Level 11). Potent Cantrip: Deals half damage on a missed attack roll.",
        "content": "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack (+7). On a hit, the target takes 2d10 Fire damage. Flammable objects not being worn or carried ignite.\n\n**2024 Potent Cantrip Rule:** If your attack roll misses, the target still takes half of the damage rolled (no additional fire spreading)."
    },
    {
        "title": "Ray of Frost",
        "slug": "ray-of-frost",
        "level": 0,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "60 feet",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": True,
        "upcast_notes": "Deals 2d8 Cold at Level 7. Potent Cantrip: Deals half damage on a missed attack roll.",
        "content": "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack (+7). On a hit, the target takes 2d8 Cold damage, and its Speed is reduced by 10 feet until the start of your next turn.\n\n**2024 Potent Cantrip Rule:** If the attack misses, the target takes half damage (the speed reduction does not apply on a miss)."
    },
    {
        "title": "Prestidigitation",
        "slug": "prestidigitation",
        "level": 0,
        "school": "Transmutation",
        "casting_time": "1 Action",
        "range": "10 feet",
        "components": "V, S",
        "duration": "Up to 1 hour",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "Minor sensory effects, lighting/snuffing candles, cleaning or soiling objects, chilling/warming/flavoring nonliving material, making color marks, or creating small trinkets."
    },
    {
        "title": "Mage Hand",
        "slug": "mage-hand",
        "level": 0,
        "school": "Conjuration",
        "casting_time": "1 Action",
        "range": "30 feet",
        "components": "V, S",
        "duration": "1 minute",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "A spectral, floating hand appears at a point within range. You can use an Action to control the hand to manipulate an object, open an unlocked door/container, stow/retrieve an item, or pour liquid. Can carry up to 10 pounds."
    },
    {
        "title": "Message",
        "slug": "message",
        "level": 0,
        "school": "Transmutation",
        "casting_time": "1 Action",
        "range": "120 feet",
        "components": "V, S, M (a short piece of copper wire)",
        "duration": "1 round",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Granted via Magic Initiate origin feat.",
        "content": "You point toward a creature within range and whisper a message. The target (and only the target) hears the message and can whisper a reply that only you can hear. Passes through solid objects (blocked by 1 ft stone, 1 inch metal, or thin lead)."
    },
    {
        "title": "Minor Illusion",
        "slug": "minor-illusion",
        "level": 0,
        "school": "Illusion",
        "casting_time": "1 Action",
        "range": "30 feet",
        "components": "S, M (a bit of fleece)",
        "duration": "1 minute",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Granted via Magic Initiate origin feat.",
        "content": "You create a sound or an image of an object within range that lasts for the duration. The illusion ends if you dismiss it as an action or cast this spell again. Physical interaction reveals it as an illusion."
    },

    # Level 1 Spells
    {
        "title": "Shield",
        "slug": "shield",
        "level": 1,
        "school": "Abjuration",
        "casting_time": "1 Reaction",
        "range": "Self",
        "components": "V, S",
        "duration": "1 round",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "1 Free cast per Long Rest via Magic Initiate; can also cast using spell slots.",
        "content": "Trigger: You are hit by an attack roll or targeted by Magic Missile. You gain a +5 bonus to AC (turning AC 15 into AC 20 with Mage Armor) until the start of your next turn, and you take no damage from Magic Missile."
    },
    {
        "title": "Mage Armor",
        "slug": "mage-armor",
        "level": 1,
        "school": "Abjuration",
        "casting_time": "1 Action",
        "range": "Touch",
        "components": "V, S, M (a piece of cured leather)",
        "duration": "8 hours",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "You touch a willing creature who isn't wearing armor. The target's base AC becomes 13 + its Dexterity modifier (+2), giving Joe AC 15 for 8 hours without requiring concentration."
    },
    {
        "title": "Thunderwave",
        "slug": "thunderwave",
        "level": 1,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "Self (15-foot cube)",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": True,
        "potent_cantrip": False,
        "upcast_notes": "+1d8 thunder damage per slot level above 1st. Sculpt Spells protects up to 2 allies.",
        "content": "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you makes a DC 15 Constitution save. On a fail, takes 2d8 Thunder damage and is pushed 10 feet away. Unsecured objects are pushed 10 feet. Emits a thunderous boom audible up to 300 feet."
    },
    {
        "title": "Chromatic Orb",
        "slug": "chromatic-orb",
        "level": 1,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "90 feet",
        "components": "V, S, M (a diamond worth at least 50 GP, owned/reusable)",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "+1d8 damage per slot level above 1st.",
        "content": "You hurl a 4-inch sphere of energy at a creature. Make a ranged spell attack (+7). On hit, deals 3d8 damage of chosen type (Acid, Cold, Fire, Lightning, Poison, or Thunder). Requires the 50 GP diamond component (confirmed owned)."
    },
    {
        "title": "Grease",
        "slug": "grease",
        "level": 1,
        "school": "Conjuration",
        "casting_time": "1 Action",
        "range": "60 feet (10-foot square)",
        "components": "V, S, M (a bit of pork rind or butter)",
        "duration": "1 minute",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "Slick grease covers the ground in a 10-foot square. The area is difficult terrain. When grease appears, each creature standing in its area must succeed on a DC 15 Dexterity saving throw or fall Prone. A creature that enters the area or ends its turn there must also save."
    },
    {
        "title": "Detect Magic",
        "slug": "detect-magic",
        "level": 1,
        "school": "Divination",
        "casting_time": "1 Action (or +10 mins as Ritual)",
        "range": "Self (30-foot sphere)",
        "components": "V, S",
        "duration": "Concentration, up to 10 minutes",
        "concentration": True,
        "ritual": True,
        "prepared": False,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Cast as a Ritual directly from Spellbook without preparation.",
        "content": "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic."
    },
    {
        "title": "Find Familiar",
        "slug": "find-familiar",
        "level": 1,
        "school": "Conjuration",
        "casting_time": "1 Hour (or +10 mins as Ritual)",
        "range": "10 feet",
        "components": "V, S, M (10 GP worth of incense, consumed)",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": True,
        "prepared": False,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Summons or re-embodies Cow (Tiny Fey familiar using Owl stat block).",
        "content": "You gain the service of Cow, a familiar that takes the form of an Owl housed in the wooden toy Mr. Big. Cow rolls own initiative, can take Help and other non-attack actions, and can deliver touch spells within 100 ft using its Reaction."
    },
    {
        "title": "Alarm",
        "slug": "alarm",
        "level": 1,
        "school": "Abjuration",
        "casting_time": "1 Minute (or +10 mins as Ritual)",
        "range": "30 feet (20-foot cube)",
        "components": "V, S, M (a tiny bell and piece of silver wire)",
        "duration": "8 hours",
        "concentration": False,
        "ritual": True,
        "prepared": False,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Cast as a Ritual directly from Spellbook without preparation.",
        "content": "You set an alarm against unwanted intrusion. Choose a door, window, or area within range. When a Tiny or larger creature touches or enters the warded area without speaking the password, an alarm is triggered (mental ping within 1 mile or audible bell)."
    },
    {
        "title": "Burning Hands",
        "slug": "burning-hands",
        "level": 1,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "Self (15-foot cone)",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": True,
        "potent_cantrip": False,
        "upcast_notes": "+1d6 fire damage per slot level above 1st. Sculpt Spells protects up to 2 allies.",
        "content": "A thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone makes a DC 15 Dexterity save: 3d6 Fire damage on fail, half on pass. Sculpt Spells protects up to 2 allies (auto-success, 0 damage). Flammable objects ignite."
    },

    # Level 2 Spells
    {
        "title": "Invisibility",
        "slug": "invisibility",
        "level": 2,
        "school": "Illusion",
        "casting_time": "1 Action",
        "range": "Touch",
        "components": "V, S, M (an eyelash encased in gum arabic)",
        "duration": "Concentration, up to 1 hour",
        "concentration": True,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Targets one additional creature for each slot level above 2nd.",
        "content": "A creature you touch becomes invisible until the spell ends. The spell ends early if the target attacks or casts a spell."
    },
    {
        "title": "Misty Step",
        "slug": "misty-step",
        "level": 2,
        "school": "Conjuration",
        "casting_time": "1 Bonus Action",
        "range": "Self (30 feet)",
        "components": "V",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see. Instant escape from grapples and melee engagement without provoking opportunity attacks."
    },
    {
        "title": "Mirror Image",
        "slug": "mirror-image",
        "level": 2,
        "school": "Illusion",
        "casting_time": "1 Action",
        "range": "Self",
        "components": "V, S",
        "duration": "1 minute",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "Three illusory duplicates of yourself appear in your space. Each time a creature targets you with an attack, roll a d20 to determine whether the attack targets a duplicate (6+ with 3 images, 8+ with 2, 11+ with 1). A duplicate's AC is 10 + Dex mod (+2) = 12. Destroyed on hit."
    },
    {
        "title": "Web",
        "slug": "web",
        "level": 2,
        "school": "Conjuration",
        "casting_time": "1 Action",
        "range": "60 feet (20-foot cube)",
        "components": "V, S, M (a bit of spiderweb)",
        "duration": "Concentration, up to 1 hour",
        "concentration": True,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "You conjure a mass of thick, sticky webbing. Area is difficult terrain and lightly obscured. Creatures starting turn or entering webs make a DC 15 Dex save or become Restrained. Flammable: burns for 2d4 fire damage."
    },
    {
        "title": "Scorching Ray",
        "slug": "scorching-ray",
        "level": 2,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "120 feet",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "+1 additional ray per slot level above 2nd.",
        "content": "You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack (+7) for each ray. On hit, the target takes 2d6 Fire damage."
    },
    {
        "title": "Gust of Wind",
        "slug": "gust-of-wind",
        "level": 2,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "Self (60-foot line)",
        "components": "V, S, M (a legume seed)",
        "duration": "Concentration, up to 1 minute",
        "concentration": True,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": True,
        "potent_cantrip": False,
        "upcast_notes": "Sculpt Spells protects up to 3 allies.",
        "content": "A line of strong wind 60 feet long and 10 feet wide blasts from you. Each creature starting turn in line makes DC 15 Strength save: pushed 15 feet away. Moving closer costs 2 extra feet of movement per foot. Disperses gas and vapors."
    },

    # Level 3 Spells
    {
        "title": "Fireball",
        "slug": "fireball",
        "level": 3,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "150 feet (20-foot sphere)",
        "components": "V, S, M (a ball of bat guano and sulfur)",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": True,
        "potent_cantrip": False,
        "upcast_notes": "+1d6 fire damage and +1 protected creature per slot level above 3rd.",
        "content": "A bright streak flashes to a point within range and blossoms into an explosion of flame. 20-foot radius sphere. DC 15 Dexterity save: 8d6 Fire damage on fail, half on pass. Sculpt Spells protects up to 4 allies (auto-success, 0 damage). Ignites flammable objects."
    },
    {
        "title": "Lightning Bolt",
        "slug": "lightning-bolt",
        "level": 3,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "Self (100-foot line)",
        "components": "V, S, M (a bit of fur and a rod of amber, crystal, or glass)",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": True,
        "potent_cantrip": False,
        "upcast_notes": "+1d6 lightning damage and +1 protected creature per slot level above 3rd.",
        "content": "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you. Each creature in line makes a DC 15 Dexterity save: 8d6 Lightning damage on fail, half on pass. Sculpt Spells protects up to 4 allies (auto-success, 0 damage)."
    },
    {
        "title": "Counterspell",
        "slug": "counterspell",
        "level": 3,
        "school": "Abjuration",
        "casting_time": "1 Reaction",
        "range": "60 feet",
        "components": "S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Automatically counters spells of equal or lower slot level.",
        "content": "Trigger: You see a creature within 60 feet casting a spell. If the spell is 3rd level or lower, it fails with no effect. If 4th level or higher, make an Intelligence check (DC 10 + spell level) with Joe's +7 modifier."
    },
    {
        "title": "Dispel Magic",
        "slug": "dispel-magic",
        "level": 3,
        "school": "Abjuration",
        "casting_time": "1 Action",
        "range": "120 feet",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Automatically ends spells of equal or lower slot level.",
        "content": "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For spells of 4th level or higher, make an Intelligence check (DC 10 + spell level) with Joe's +7 modifier."
    },
    {
        "title": "Fly",
        "slug": "fly",
        "level": 3,
        "school": "Transmutation",
        "casting_time": "1 Action",
        "range": "Touch",
        "components": "V, S, M (a wing feather from any bird)",
        "duration": "Concentration, up to 10 minutes",
        "concentration": True,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "Targets one additional creature for each slot level above 3rd.",
        "content": "You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall."
    },

    # Level 4 Spells
    {
        "title": "Ice Storm",
        "slug": "ice-storm",
        "level": 4,
        "school": "Evocation",
        "casting_time": "1 Action",
        "range": "300 feet (20-foot radius, 40-foot high cylinder)",
        "components": "V, S, M (a pinch of dust and a few drops of water)",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": False,
        "sculpt_spells": True,
        "potent_cantrip": False,
        "upcast_notes": "+1d8 bludgeoning damage and +1 protected creature per slot level above 4th.",
        "content": "A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. DC 15 Dexterity save: 2d8 Bludgeoning + 4d6 Cold damage on fail, half on pass. Sculpt Spells protects up to 5 allies (auto-success, 0 damage). Area becomes difficult terrain until end of your next turn."
    },
    {
        "title": "Arcane Eye",
        "slug": "arcane-eye",
        "level": 4,
        "school": "Divination",
        "casting_time": "1 Action",
        "range": "30 feet",
        "components": "V, S, M (a bit of bat fur)",
        "duration": "Concentration, up to 1 hour",
        "concentration": True,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and Darkvision 30 feet in all directions. As an action, you can move the eye up to 30 feet in any direction (can pass through small openings as small as 1 inch)."
    },
    {
        "title": "Dimension Door",
        "slug": "dimension-door",
        "level": 4,
        "school": "Conjuration",
        "casting_time": "1 Action",
        "range": "500 feet",
        "components": "V",
        "duration": "Instantaneous",
        "concentration": False,
        "ritual": False,
        "prepared": True,
        "sculpt_spells": False,
        "potent_cantrip": False,
        "upcast_notes": "",
        "content": "You teleport yourself to any other spot within 500 feet. You arrive at exactly the spot desired. You can bring along objects and one willing creature of your size or smaller who is carrying gear up to its carrying capacity (must be within 5 feet of you)."
    }
]

os.makedirs('content/spellbook', exist_ok=True)

for s in spells_data:
    frontmatter = f"""---
title: "{s['title']}"
level: {s['level']}
school: "{s['school']}"
casting_time: "{s['casting_time']}"
range: "{s['range']}"
components: "{s['components']}"
duration: "{s['duration']}"
concentration: {'true' if s['concentration'] else 'false'}
ritual: {'true' if s['ritual'] else 'false'}
prepared: {'true' if s['prepared'] else 'false'}
sculpt_spells: {'true' if s['sculpt_spells'] else 'false'}
potent_cantrip: {'true' if s['potent_cantrip'] else 'false'}
upcast_notes: "{s['upcast_notes']}"
---

{s['content']}
"""
    with open(f"content/spellbook/{s['slug']}.md", 'w', encoding='utf-8') as f:
        f.write(frontmatter)

print(f"Generated all {len(spells_data)} spells and cantrips in content/spellbook/")
